### PR TITLE
fix: Assign NA values instead of filtering snpCor 

### PR DESCRIPTION
**Pull request by sof202**
# Description

This pull request will attempt to fix the issues that come with having samples fail the QC. Before, if a sample failed QC, it was removed from snpCor. This causes problems as `predictedduplicates` can have less entries than `QCmetrics` has rows. The updated method ignores these samples, rather than remove them.

## Issue ticket number

This pull request is to address issue: #179.

## Type of pull request

- [x] Bug fix
- [ ] New feature/enhancement
- [x] Code refactor
- [ ] Documentation update

## Checklist

- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested my code to check that it is functional
- [x] I have used linters to check for common sources of errors
- [ ] I have implemented fail safes in my code to account for edge cases
- [ ] I have made the corresponding changes to the documentation

### CODE REVIEW

**Comment by dmsoanes** [comment]
I have tested the new code (https://github.com/ejh243/BrainFANS/blob/snpcor-subsetting/array/DNAm/preprocessing/QC.rmd) and got a different error:
Files uploaded - other data can be found at /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN
```
processing file: QC.rmd
Error:
! object 'snpCor.temp' not found
Backtrace:
 1. global findDuplicateSamples(snpCor)
Warning message:
In in_dir(input_dir(), expr) :
  You changed the working directory to /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN (probably via setwd()). It will be restored to /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN/original_scripts/BrainFANS/array/DNAm/preprocessing. See the Note section in ?knitr::knit

Quitting from lines 515-541 [findDuplicateSamples] (QC.rmd)
Execution halted
```
[config.r.txt](https://github.com/user-attachments/files/16784679/config.r.txt)
[config.txt](https://github.com/user-attachments/files/16784680/config.txt)
[PassQCStatusAllSamples.csv](https://github.com/user-attachments/files/16784681/PassQCStatusAllSamples.csv)
[QCDNAdata_2559367.err.txt](https://github.com/user-attachments/files/16784682/QCDNAdata_2559367.err.txt)
[QCDNAdata_2559367.log](https://github.com/user-attachments/files/16784683/QCDNAdata_2559367.log)
[QCMetricsPostSampleCheck.csv](https://github.com/user-attachments/files/16784684/QCMetricsPostSampleCheck.csv)
[SexMismatches.csv](https://github.com/user-attachments/files/16784686/SexMismatches.csv)

**Comment by sof202** [comment]
My bad Darren. Typo on my part. Fixed now.

**Comment by dmsoanes** [comment]
Tested the code again - different error this time

```
processing file: QC.rmd


processing file: ./rmarkdownChild/sexCheck.rmd
Error in `!passQC`:
! invalid argument type
Warning message:
In in_dir(input_dir(), expr) :
  You changed the working directory to /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN (probably via setwd()). It will be restored to /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN/original_scripts/BrainFANS/array/DNAm/preprocessing. See the Note section in ?knitr::knit

Quitting from lines 874-889 [findDuplicateSamplesPostQC] (QC.rmd)
Execution halted
```
[config.r.txt](https://github.com/user-attachments/files/16785335/config.r.txt)
[config.txt](https://github.com/user-attachments/files/16785336/config.txt)
[PassQCStatusAllSamples.csv](https://github.com/user-attachments/files/16785337/PassQCStatusAllSamples.csv)
[QCDNAdata_2641732.err.txt](https://github.com/user-attachments/files/16785338/QCDNAdata_2641732.err.txt)
[QCDNAdata_2641732.log](https://github.com/user-attachments/files/16785339/QCDNAdata_2641732.log)
[QCMetricsPostSampleCheck.csv](https://github.com/user-attachments/files/16785340/QCMetricsPostSampleCheck.csv)

**Comment by sof202** [comment]
> Tested the code again - different error this time
> 
> ```
> processing file: QC.rmd
> 
> 
> processing file: ./rmarkdownChild/sexCheck.rmd
> Error in `!passQC`:
> ! invalid argument type
> Warning message:
> In in_dir(input_dir(), expr) :
>   You changed the working directory to /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN (probably via setwd()). It will be restored to /lustre/projects/Research_Project-MRC190311/DNAm/Darren/OHSU_006PLT_JN/original_scripts/BrainFANS/array/DNAm/preprocessing. See the Note section in ?knitr::knit
> 
> Quitting from lines 874-889 [findDuplicateSamplesPostQC] (QC.rmd)
> Execution halted
> ```
> 
> [config.r.txt](https://github.com/user-attachments/files/16785335/config.r.txt) [config.txt](https://github.com/user-attachments/files/16785336/config.txt) [PassQCStatusAllSamples.csv](https://github.com/user-attachments/files/16785337/PassQCStatusAllSamples.csv) [QCDNAdata_2641732.err.txt](https://github.com/user-attachments/files/16785338/QCDNAdata_2641732.err.txt) [QCDNAdata_2641732.log](https://github.com/user-attachments/files/16785339/QCDNAdata_2641732.log) [QCMetricsPostSampleCheck.csv](https://github.com/user-attachments/files/16785340/QCMetricsPostSampleCheck.csv)

Fixed also (the code was still using sample names, which can't be negated)

**Review by dmsoanes — APPROVED** [review]
Have tested code - now produces QC.html with summary of QC

**Pull request merged**
